# generated by generate_router.py
# DO NOT EDIT MANUALLY - regenerate using: python3 generate_router.py

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any


class HealthGetResponse(BaseModel):
    status: Optional[str] = Field(None, examples=['healthy'])


class HelloGetResponse(BaseModel):
    message: Optional[str] = Field(None, examples=['Hello from FastAPI'])


class ProtectedGetResponse(BaseModel):
    message: Optional[str] = Field(None, examples=['This is a protected endpoint'])


class ProtectedGetResponse401(BaseModel):
    detail: Optional[str] = Field(None, examples=['Invalid authentication credentials'])

