# backend/ruff.toml
line-length = 160
target-version = "py314"

[lint]
# Enable Pyflakes (F) and Isort (I) rules by default
select = ["E", "F", "I", "W"]
ignore = ["E501"] # Ignore line length violations

[format]
quote-style = "double"
indent-style = "space"